num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
print("The sum is", num1 + num2)
print("The difference is", num1 - num2)
print("The product is", num1 * num2)
print("The quotient is", num1 / num2)
